### ISSUE TITLE
Y24-046: Fix SSL issue in the integration suite when trying to establish connection(s) with other services

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/General-Backlog-Items#379]
**Describe the bug**

Job [#1228611](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/jobs/1228611) in GitLab CI for the integration suite failed for [5822836c](https://github.com/psd/integration-suite/-/commit/5822836cec5f85eb4cac9142b6146b6e45b96f85):

The reason is that the Docker container fails to establish the SSL connection between itself (i.e., the container) and services like `baracoda`. It is likely that some modifications are required in the docker image itself regarding the new SSL certificate.

**To Reproduce**

This issue can be reproduced trivially by running the integration suite pipeline's `master` branch, without choosing individual tests. Or, it could be done by running only the `health_check_spec.rb` rspec.

To diagnose and troubleshoot the issue locally, we can build the image in a local development environment, run it in a container and try to run the `health_check_spec.rb`. Make sure that you have [Docker installed](https://docs.docker.com/desktop/install/mac-install/) in the local environment.

Note that the `--platform` flag needs to be provided for an M1-series Macbook. Navigate to the `integration-suite` project in your local development environment before running these commands.

```
$ docker build --platform=linux/amd64 -t integration-suite .
$ docker run -it integration-suite bash
```

Once logged into the container using the bash command above, use the following command to run the test.

```
$ ENVIRONMENT=uat bundle exec rspec spec/health_check_spec.rb
```

For more information about the new SSL certificate, please have a look at the [hyperlinked GitHub story](https://github.com/sanger/General-Backlog-Items/issues/371).

**Expected behaviour**

Docker container should successfully connect with the services following a proper SSL handshake. 

**Screenshots**
 
For logs, please navigate to GitLab CI Job [#1228611](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/jobs/1228611).

**Comment by dasunpubudumal** [comment]
Please find the error logs below:

```
Failures:

  1) Health check applications running in UAT GET requests to the homepage returns http success for gatekeeper
     Failure/Error: response = RestClient.get(UAT_URLS[:gatekeeper_url])

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.22.121:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.22.121:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  2) Health check applications running in UAT GET requests to the homepage returns http success for sm_workflow
     Failure/Error: response = RestClient.get(UAT_URLS[:sm_workflow_url])

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.20.16:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:30:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.20.16:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  3) Health check applications running in UAT GET requests to the homepage returns http success for baracoda
     Failure/Error: response = RestClient.get("#{UAT_URLS[:baracoda_url]}/health")

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.23.84:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:40:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.23.84:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  4) Health check applications running in UAT GET requests to the homepage returns http success for quanthub
     Failure/Error: response = RestClient.get(UAT_URLS[:quanthub_url])

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.21.157:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.21.157:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  5) Health check applications running in UAT GET requests to the homepage returns http success for asset_audits
     Failure/Error: response = RestClient.get(UAT_URLS[:asset_audits_url])

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.19.145:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:35:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.19.145:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  6) Health check applications running in UAT GET requests to the homepage returns http success for traction_ui
     Failure/Error: response = RestClient.get(UAT_URLS[:traction_ui_url])

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.20.86:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.20.86:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  7) Health check applications running in UAT GET requests to the homepage returns http success for print_my_barcode
     Failure/Error: response = RestClient.get("#{UAT_URLS[:print_my_barcode_url]}/v2/printers")

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.16.73:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:45:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.16.73:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'

  8) Health check applications running in UAT GET requests to the homepage returns http success for labwhere
     Failure/Error: response = RestClient.get(UAT_URLS[:labwhere_url])

     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 peeraddr=172.27.22.8:443 state=error: certificate verify failed (unable to get local issuer certificate)
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:776:in `rescue in transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
     # ./spec/health_check_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenSSL::SSL::SSLError:
     #   SSL_connect returned=1 errno=0 peeraddr=172.27.22.8:443 state=error: certificate verify failed (unable to get local issuer certificate)
     #   /usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
```

These logs can be replicated through the process mentioned above in the story.
