### ISSUE TITLE
Y25-387 - Programmatically set the y24_220_enable_tag_set_api flipper flag prior to int-suite running

### ISSUE THREAD

**Issue by StephenHulme** [sanger/General-Backlog-Items#599]
**Describe the Housekeeping**
In training, the flipper flag for the tag sets keeps getting reset (`y24_220_enable_tag_set_api`)
Write a before fixture to set the flag to the correct value prior to the suite running.

**Suggested solution**
In `config.before(:suite) do` in `spec/spec_helper.rb`:
 ```
  Capybara.visit("https://training.sequencescape.psd.sanger.ac.uk/flipper/features/y24_220_enable_tag_set_api")
  if there is text saying "Fully enabled"
     press the button saying "Disable"
     when a popup box appears, enter the text `y24_220_enable_tag_set_api`
  ```
Then proceed with tests.

**Stretch goal**
The immediate need is to address this specific feature-flag, but this would be a very useful feature to have generally in int-suite.

A config-driven solution where there is a file defining those flags that we would like to set explicitly would be ideal. It could be a yaml file that looks something like this?
```yml
# feature-flags.yml

# Explicitly sets the flags below to their desired states at the start of the test run 
# - don't forget to set them back afterwards!
# 
# example:
# feature_we_want: enable
# feature_we_do_not_want: disable

y24_220_enable_tag_set_api: enable
other_feature_we_do_not_want: disable
```

**Alternatives**
Alternatively these stories would solve the issue too: https://github.com/sanger/sequencescape/issues/4766

**Blocking issues**
None

**Additional context**
See https://psd-team.slack.com/archives/C07TRSCTA1Y/p1746004211552579
And countless times that tests have failed since the flag has been incorrectly configured.
It's also caused a release to be delayed to the next week.

This should be an hour to inplement and another hour to test... 🤞
